name: base_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.3.1
  flutter_riverpod: ^3.0.0-dev.17
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  google_sign_in: ^7.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  retrofit: ^4.7.2
  riverpod_annotation: ^3.0.0-dev.17
  flutter_svg: ^2.2.1
  riverpod: ^3.0.0-dev.17
  dio: ^5.9.0
  go_router: ^16.2.1
  sparkit:
    git: https://github.com/sparko-labs/sparkit_flutter.git
  shared_preferences: ^2.5.3
  flutter_gen: ^5.11.0
  reusables:
    git:
      url: https://github.com/SparkoSol/reusables.git
      ref: migration
  collection: ^1.19.1
  sqflite: ^2.4.2
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  cached_network_image: ^3.4.1
  firebase_storage: ^13.0.1
  purchases_flutter: ^9.4.0
  sign_in_with_apple: ^7.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.28.1
  riverpod_generator:
  build_runner:
  flutter_gen_runner: ^5.11.0
  json_serializable:
  retrofit_generator:
  riverpod_lint: ^3.0.0-dev.17
  freezed: ^3.2.0
  in_app_purchase_platform_interface: ^1.4.0

  flutter_lints: ^6.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_gen:
  assets:
    exclude:
      - assets/flags/**
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_image.png
  android: true
  ios: true

  android_12:
    image: assets/images/logo_image.png

  web: false